:aa::=aa:~aa
~aa::=~a
:ab::=ab:~ab
~ab::=~b
:ba::=ba:~ba
~ba::=~c
:bb::=bb:~bb
~bb::=~:
:bc::=bc:~bc
~bc::=~=
:cb::=cb:~cb
~cb::=~~
:cc::=cc:~cc
~cc::=~
::::==
aa=::==aa
ab=::==ab
ba=::==ba
bb=::==bb
bc=::==bc
cb=::==cb
cc=::==cc
==aa::==a~a=
a~a::=~aa
==ab::==a~b=
a~b::=~ab
==ba::==b~a=
b~a::=~ba
==bb::==b~b=
b~b::=~bb
==bc::==b~c=
b~c::=~bc
==cb::==c~b=
c~b::=~cb
==cc::==c~c=
c~c::=~cc
==~::=~:~
::=
=:bbaaaabbbbbcaaaabbcbaaaacccbaaaabbbbbccbaaccbbaaabbbbbbcaaabbbcbaaabcccbaaabbbbbbccbabccbbabaabbbbbcabaabbcbabaacccbabaabbbbbccbbaccbbababbbbbbcababbbcbababcccbababbbbbbccbbbccbbabbabbbbbcabbabbcbabbacccbabbabbbbbccbbcccbbbaabbbbbbcbaabbbcbbaabcccbbaabbbbbbccbcbccbbbababbbbbcbababbcbbabacccbbababbbbbccbccbbbbbbbbbcbcccaaaabcbbbbbcbcaaaaccaaabbcbbbbbcbcaaabccabaabcbbbbbcbcabaaccababbcbbbbbcbcababccabbabcbbbbbcbcabbaccbaabbcbbbbbcbcbaabccbababcbbbbbcbcbabaccbcbcaaaabbbbbcbcaacbaabcccaacbaabbbbbccbaaaaccbcbcaaabbbbbbcbcaacbabbcccaacbabbbbbbccbaaabccbcbcabaabbbbbcbcabcbaabcccabcbaabbbbbccbabaaccbcbcababbbbbbcbcabcbabbcccabcbabbbbbbccbababccbcbcabbabbbbbcbcabcbbabcccabcbbabbbbbccbabbaccbcbcbaabbbbbbcbcbacbabbcccbacbabbbbbbccbbaabccbcbcbababbbbbcbcbacbbabcccbacbbabbbbbccbbabaccbcbccbbbbbbccbbbcbccbbbbbcccbcbb:~
